const { stringCol, boolCol, dateCol, intCol, arrCol } = require("./common");
const database = require("../utils/database");

const trendRepositoriesModel = database.define("trendRepositories", {
  pKey: intCol({ primaryKey: true, unique: true, autoIncrement: true }),
  id: intCol(),
  node_id: stringCol({ allowNull: true }),
  name: stringCol({ allowNull: true }),
  full_name: stringCol({ allowNull: true }),
  private: boolCol(),
  owner: intCol({
    allowNull: true,
    references: {
      model: "owners",
      key: "id",
    },
  }),
  html_url: stringCol({ allowNull: true }),
  description: stringCol({ allowNull: true }),
  fork: boolCol(),
  url: stringCol({ allowNull: true }),
  forks_url: stringCol({ allowNull: true }),
  keys_url: stringCol({ allowNull: true }),
  collaborators_url: stringCol({ allowNull: true }),
  teams_url: stringCol({ allowNull: true }),
  hooks_url: stringCol({ allowNull: true }),
  issue_events_url: stringCol({ allowNull: true }),
  events_url: stringCol({ allowNull: true }),
  assignees_url: stringCol({ allowNull: true }),
  branches_url: stringCol({ allowNull: true }),
  tags_url: stringCol({ allowNull: true }),
  blobs_url: stringCol({ allowNull: true }),
  git_tags_url: stringCol({ allowNull: true }),
  git_refs_url: stringCol({ allowNull: true }),
  trees_url: stringCol({ allowNull: true }),
  statuses_url: stringCol({ allowNull: true }),
  languages_url: stringCol({ allowNull: true }),
  stargazers_url: stringCol({ allowNull: true }),
  contributors_url: stringCol({ allowNull: true }),
  subscribers_url: stringCol({ allowNull: true }),
  subscription_url: stringCol({ allowNull: true }),
  commits_url: stringCol({ allowNull: true }),
  git_commits_url: stringCol({ allowNull: true }),
  comments_url: stringCol({ allowNull: true }),
  issue_comment_url: stringCol({ allowNull: true }),
  contents_url: stringCol({ allowNull: true }),
  compare_url: stringCol({ allowNull: true }),
  merges_url: stringCol({ allowNull: true }),
  archive_url: stringCol({ allowNull: true }),
  downloads_url: stringCol({ allowNull: true }),
  issues_url: stringCol({ allowNull: true }),
  pulls_url: stringCol({ allowNull: true }),
  milestones_url: stringCol({ allowNull: true }),
  notifications_url: stringCol({ allowNull: true }),
  labels_url: stringCol({ allowNull: true }),
  releases_url: stringCol({ allowNull: true }),
  deployments_url: stringCol({ allowNull: true }),
  created_at: dateCol(),
  updated_at: dateCol(),
  pushed_at: dateCol(),
  git_url: stringCol({ allowNull: true }),
  ssh_url: stringCol({ allowNull: true }),
  clone_url: stringCol({ allowNull: true }),
  svn_url: stringCol({ allowNull: true }),
  homepage: stringCol({ allowNull: true }),
  size: intCol({ allowNull: true }),
  stargazers_count: intCol({ allowNull: true }),
  watchers_count: intCol({ allowNull: true }),
  language: stringCol({ allowNull: true }),
  has_issues: boolCol(),
  has_projects: boolCol(),
  has_downloads: boolCol(),
  has_wiki: boolCol(),
  has_pages: boolCol(),
  has_discussions: boolCol(),
  forks_count: intCol({ allowNull: true }),
  mirror_url: stringCol({ allowNull: true }),
  archived: boolCol(),
  disabled: boolCol(),
  open_issues_count: intCol({ allowNull: true }),
  license: stringCol({
    allowNull: true,
    references: {
      model: "licenses",
      key: "key",
    },
  }),
  allow_forking: boolCol(),
  is_template: boolCol(),
  web_commit_signoff_required: boolCol(),
  topics: arrCol(stringCol({ allowNull: true })),
  visibility: stringCol({ allowNull: true }),
  forks: intCol({ allowNull: true }),
  open_issues: intCol({ allowNull: true }),
  watchers: intCol({ allowNull: true }),
  default_branch: stringCol({ allowNull: true }),
  temp_clone_token: stringCol({ allowNull: true }),
  network_count: intCol({ allowNull: true }),
  subscribers_count: intCol({ allowNull: true }),
});

module.exports = trendRepositoriesModel;
